title = "giuseppesamela.com"
baseURL = "https://giuseppesamela.com"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Bari, IT"
workProfile = "Software Engineer"
email = "giuseppe.samela@gmail.com"
favicon = "/favicon.ico"
firstName = "Giuseppe"
lastName = "Samela"
profileImage = "img/profile.jpg"
showOpenSource = false
showProjects = false
showPublications = false
showEducation = true
showExperience = true
showQr = true
showSkills = false

[params.google]

[params.google.analytics]
trackerID = "UA-164223983-1"

[[params.handles]]
link = "https://twitter.com/wasp898"
name = "Twitter"

[[params.handles]]
link = "https://www.facebook.com/g.samela"
name = "Facebook"

[[params.handles]]
link = "https://www.linkedin.com/in/giuseppe-samela-011536137/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/wasp898/"
name = "GitHub"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"